apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: myapp-first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.90-192.168.1.110

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - myapp-first-pool
